AWSTemplateFormatVersion: "2010-09-09"
Transform: "AWS::Serverless-2016-10-31"

Parameters:
  Stage:
    Type: String
  ProjectName:
    Type: String

Outputs:
  PythonDepLayerArn:
    Description: "Lambda Layer Arn"
    Value: !Ref PythonDependencyLayer

Resources:
  PythonDependencyLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: !Sub "${ProjectName}-${Stage}-python-deps"
      CompatibleRuntimes:
        - python3.8
      ContentUri: ./../.build/dependencies
      RetentionPolicy: Delete
